
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'Formula1'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  Formula1:
    # Applies to all files under models/example/
    example:
      materialized: view

seeds:
  Formula1:
    kaggle_F1_data:
      +schema: raw
      pit_stops:
        +column_types:
          time: TIME(2)
          duration: NUMBER(38,3)
      qualifying:
        +column_types:
          Q1: TIME(3)
          Q2: TIME(3)
          Q3: TIME(3)
      races:
        +column_types:
          time: TIME(2)
          fp1_date: DATE
          fp1_time: TIME(2)
          fp2_date: DATE
          fp2_time: TIME(2)
          fp3_date: DATE
          fp3_time: TIME(2)
          quali_date: DATE
          quali_time: TIME(2)
          sprint_date: DATE
          sprint_time: TIME(2)
      results:
        +column_types:
          fastestlaptime: TIME(3)
          fastestlapspeed: NUMBER(38,3)
      sprint_results:
        +column_types:
          fastestlaptime: TIME(3)
          fastestlapspeed: NUMBER(38,3)

